Vagrant.configure("2") do |config|
    
    config.vm.define "attacker" do |attacker|
        attacker.vm.box = "elrey741/kali-linux_amd64"
        attacker.vm.hostname = 'attacker'

        attacker.vm.network :public_network, ip: "10.0.0.190", bridge: "wlp0s20f3"

        attacker.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--memory", 4096]
            v.customize ["modifyvm", :id, "--name", "attacker"]
        end

        attacker.vm.provision :ansible do |ansible|
            ansible.playbook = "ansible/playbook.yml"
        end
    
    end

    config.vm.define "target" do |target|
        target.vm.box = "peru/windows-server-2019-standard-x64-eval"
        target.vm.hostname = 'target'

        target.vm.network :public_network, ip: "10.0.0.191", bridge: "wlp0s20f3"

        target.vm.provision :shell,  privileged: true, path: "shell/configure_firewall.cmd"
        target.vm.provision :shell,  privileged: true, path: "shell/install_ansible_remote.cmd"

        target.vm.provider :virtualbox do |v|
            v.customize ["modifyvm", :id, "--memory", 4096]
            v.customize ["modifyvm", :id, "--name", "target"]
        end

        target.vm.provision :ansible do |ansible|
            ansible.playbook = "ansible_windows/playbook.yml"
        end
    
    end
end