---
- name: update cache & full system update
  become: yes
  become_method: sudo
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: install python3
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: python3
    state: latest

- name: install python3-venv
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: python3-venv
    state: latest
    
- name: install pip3
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes
    name: python3-pip 
    state: latest


- name: install python3-dev
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes
    name: python3-dev 
    state: latest

- name: install python-dev
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes
    name: python-dev 
    state: latest

- name: install python packages
  pip:
    name: 
    - pycrypto
    - termcolor

- name: install apache2
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    name: apache2
    state: latest
